### ISSUE TITLE
Clone only the needed branch to speed things up

### ISSUE THREAD

**Issue by yocontra** [felixge/node-cross-compiler#2]
Could possible be replaced with

```
mkdir node
cd node
git init
git remote add -t ${NODE_BRANCH} -f origin ${NODE_REPO}
git checkout ${NODE_BRANCH}
```

**Comment by felixge** [comment]
Would that actually yield much benefits considering that most objects in recent node branch will usually be linked to the entire history?

**Comment by yocontra** [comment]
@felixge - It took the clone time from a minute to a few seconds in my testing

**Comment by rmehner** [comment]
Was just going to fix that, but as it is already here:

+1 to that, especially useful on hackathons where the internet connection isn't that good (like some of the connections we had at some NodeCopters)

**Comment by felixge** [comment]
@Contra / @rmehner you're both contributors now, feel free to push patches as you see fit!

**Comment by yocontra** [comment]
Sweet thanks! I've got some automated starter scripts that handle the whole process I'll put up

**Comment by yocontra** [comment]
I fixed this in master AFAIK closing it now

**Comment by felixge** [comment]
@Contra :heart: thank you so much!

**Comment by yocontra** [comment]
@felixge - Are you okay with the other changes I made?

**Comment by felixge** [comment]
> @felixge - Are you okay with the other changes I made?

Just had a look! Yes! Awesome stuff. :heart: the ftp deployment thing!
