### ISSUE TITLE
Compilation works on beagle board... perhaps don't label the make file as platform specific?

### ISSUE THREAD

**Issue by MylesBorins** [felixge/node-cross-compiler#4]
Not exactly a cross compile issue... but I wanted to let you know that the compilation works perfectly on the Beagle Board exactly the way you have it set up. I took the build folder... sent it over to my beagle board... did

``` bash
cp -r bin /usr/local/bin
sudo cd /usr/local/bin
sudo ln -s ../lib/node_modules/npm/bin/npm-cli.js npm
```

You might not need the sudo though... depending on your permissions

So yeah... both node and npm working perfectly!

**Comment by buwe** [comment]
Hello
one question... where do you took the build folder for beagle board from?
can't find it anywhere. 
thanks :-)
